honeypot:
  # Network configuration
  bind_ip: "0.0.0.0"
  
  # Service ports
  services:
    ssh:
      enabled: true
      port: 2222
      banner: "SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1"
    
    http:
      enabled: true
      port: 8080
      server_name: "Apache/2.4.41 (Ubuntu)"
    
    rdp:
      enabled: true
      port: 3389
    
    mysql:
      enabled: true
      port: 3306
      version: "8.0.33"

# Logging configuration
logging:
  level: "INFO"
  file: "../data/logs/honeyport.log"
  max_size: "10MB"
  backup_count: 5

# Database configuration
database:
  type: "sqlite"
  path: "../data/attacks.db"

# Geolocation
geolocation:
  enabled: true
  maxmind_db: "../data/GeoLite2-City.mmdb"

# Firewall integration
firewall:
  enabled: true
  auto_block: true
  block_duration: 3600  # seconds
  whitelist:
    - "127.0.0.1"
    - "192.168.1.0/24"

# Dashboard
dashboard:
  enabled: true
  host: "127.0.0.1"
  port: 5000
