apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeyport-core
  namespace: honeyport
  labels:
    app: honeyport-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeyport-core
  template:
    metadata:
      labels:
        app: honeyport-core
    spec:
      hostNetwork: true
      containers:
      - name: honeyport-core
        image: honeyport/core:latest
        ports:
        - containerPort: 2222
          name: ssh
        - containerPort: 8080
          name: http
        - containerPort: 3389
          name: rdp
        - containerPort: 3306
          name: mysql
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: honeyport-data-pvc
      - name: config-volume
        configMap:
          name: honeyport-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-backend
  namespace: honeyport
  labels:
    app: dashboard-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-backend
  template:
    metadata:
      labels:
        app: dashboard-backend
    spec:
      containers:
      - name: dashboard-backend
        image: honeyport/dashboard-backend:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_PATH
          value: "/app/data/attacks.db"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: honeyport-data-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend
  namespace: honeyport
  labels:
    app: dashboard-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-frontend
  template:
    metadata:
      labels:
        app: dashboard-frontend
    spec:
      containers:
      - name: dashboard-frontend
        image: honeyport/dashboard-frontend:latest
        ports:
        - containerPort: 80
